name: ReactApp
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
      - name: 'setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cahce: 'npm'
      - name: 'Install Dependencies'
        run: npm install
      - name: 'NPM Build'
        run: |
            npm build
            npm test