name: CI-Outputs
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: SetUp Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: npm
            - name: install depndencies
              run: npm install
            - name: Node Linting
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: SetUp Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: npm
            - name: install depndencies
              run: npm install
            - name: app test
              run: npm run test
            - name: build
              run: npm run build
    upload-artifacts:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: SetUp Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18
                cache: npm
            - name: install depndencies
              run: npm install
            - name: build
              run: npm run build
            - name: upload-artifact
              uses: actions/upload-artifact@v4
              with:
                name: dist-output
                path: dist

        
        