name: ReactApp
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
      - name: 'setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cahce: 'npm'
      - name: 'Install Dependencies'
        run: npm install
      - name: 'NPM Build'
        run: |
            npm run build
            npm test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-output
          path: dist