name: ReactApp
on: 
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
      - name: 'setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm install
      - name: 'NPM Build'
        run: |
            npm run lint
            npm run build
            npm test

  build:
    runs-on: ubuntu-latest
    needs: test
    outputs:
      artifact_id: ${{ steps.upload-artifact-step.outputs.artifact-id }}
    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4
      - name: 'setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: 'Install Dependencies'
        run: npm install
      - name: 'NPM Build'
        run: |
            npm run lint
            npm run build
            npm test
      - name: Upload Artifacts
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with:
          name: dist-output
          path: dist
      - name: Print Uploaded Artifact id
        run: |
          echo "Artifact id : ${{ steps.upload-artifact-step.outputs.artifact-id }}"
          echo "Artifact URL: ${{ steps.upload-artifact-step.outputs.artifact-url }}"